#!/usr/bin/env bash
# Capture the reference machine's CPUID leaves (see cpuid-dump.asm).
# Needs nasm, qemu-system-x86_64 and python3. Output: docs/ref/cpuid-qemu64.txt
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
nasm -f bin -o "$work/cpuid.img" "$here/cpuid-dump.asm"
truncate -s 1M "$work/cpuid.img"
python3 "$here/qemu_trace.py" --iso none --hdd "$work/cpuid.img" \
  --out "$work/run" --seconds 5 >/dev/null
mkdir -p "$root/docs/ref"
{
  echo "# CPUID leaves seen by the guest in the reference machine"
  echo "# ($(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["qemu"])' "$work/run/manifest.json"), -cpu qemu64, TCG)."
  echo "# Generated by tools/qemu-ref/cpuid_ref.sh; format: leaf subleaf: eax ebx ecx edx"
  grep -E '^cpuid [0-9a-f]{8} [0-9a-f]{8}:' "$work/run/debugcon.log" | sed 's/^cpuid //'
} > "$root/docs/ref/cpuid-qemu64.txt"
grep -q 'cpuid-dump done' "$work/run/debugcon.log"
echo "wrote docs/ref/cpuid-qemu64.txt ($(grep -vc '^#' "$root/docs/ref/cpuid-qemu64.txt") leaves)"
