#!/usr/bin/env bash
# Capture the reference machine's CPUID leaves (see cpuid-dump.asm).
# Needs nasm, qemu-system-x86_64 and python3. Output: docs/ref/cpuid-qemu64.txt,
# or with SMP=N (N > 1) docs/ref/cpuid-qemu64-smpN.txt (the BSP's view).
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
nasm -f bin -o "$work/cpuid.img" "$here/cpuid-dump.asm"
truncate -s 1M "$work/cpuid.img"
smp="${SMP:-1}"
out="$root/docs/ref/cpuid-qemu64.txt"
[ "$smp" = 1 ] || out="$root/docs/ref/cpuid-qemu64-smp$smp.txt"
python3 "$here/qemu_trace.py" --iso none --hdd "$work/cpuid.img" --smp "$smp" \
  --out "$work/run" --seconds 5 >/dev/null
mkdir -p "$root/docs/ref"
{
  echo "# CPUID leaves seen by the guest in the reference machine"
  echo "# ($(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["qemu"])' "$work/run/manifest.json"), -cpu qemu64, TCG)."
  echo "# Generated by tools/qemu-ref/cpuid_ref.sh; format: leaf subleaf: eax ebx ecx edx"
  grep -E '^cpuid [0-9a-f]{8} [0-9a-f]{8}:' "$work/run/debugcon.log" | sed 's/^cpuid //'
} > "$out"
grep -q 'cpuid-dump done' "$work/run/debugcon.log"
echo "wrote $out ($(grep -vc '^#' "$out") leaves)"
