#!/usr/bin/env python3
"""Extract device-model test fixtures from a QEMU reference trace.

The trace records the value of every device read, so the reference machine's
reset state can be recovered from it. Writes, into --out-dir (default
docs/ref/):

  pci-config-reset.txt  every PCI config read made before anything wrote
                        those bytes: "bdf reg size value"
  edid-stdvga.txt       the 256-byte EDID the std VGA exposes in BAR 2
  atapi-identify.txt    the 256 words of IDENTIFY PACKET DEVICE for the CD

The device crate's tests check the models against these files.
"""

import argparse
import os
import re

OPS = re.compile(r"memory_region_ops_(read|write) cpu -?\d+ mr \S+ addr (0x[0-9a-f]+) "
                 r"value (0x[0-9a-f]+) size (\d+) name '([^']*)'")
PCI = re.compile(r"pci_cfg_(read|write) \S+ ([0-9a-f]{2}:[0-9a-f]{2}\.[0-9a-f]) "
                 r"@(0x[0-9a-f]+) (?:->|<-) (0x[0-9a-f]+)")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("trace")
    ap.add_argument("--out-dir", default=os.path.join(ROOT, "docs", "ref"))
    args = ap.parse_args()

    written = set()          # (bdf, byte offset) written so far
    pci_reads = {}           # (bdf, reg, size) -> value, first read only
    pending = None           # PCI access waiting for its port access (size)
    edid = {}
    identify = None          # list of words while collecting, None otherwise
    identify_done = None

    with open(args.trace, errors="replace") as f:
        for line in f:
            m = PCI.search(line)
            if m:
                pending = (m[1], m[2], int(m[3], 16), int(m[4], 16))
                continue
            m = OPS.search(line)
            if not m:
                continue
            d, addr, val, size, name = m[1], int(m[2], 16), int(m[3], 16), int(m[4]), m[5]
            if pending and name == "pci-conf-data":
                pdir, bdf, reg, pval = pending
                pending = None
                span = {(bdf, reg + i) for i in range(size)}
                if pdir == "write":
                    written |= span
                elif not (span & written):
                    pci_reads.setdefault((bdf, reg, size), pval)
                continue
            if name == "edid" and d == "read":
                edid.setdefault(addr & 0xFF, val)
            if name == "ide":
                if d == "write" and addr == 0x177 and val == 0xA1 and identify_done is None:
                    identify = []
                elif identify is not None and d == "read" and addr == 0x170:
                    for i in range(size // 2):
                        identify.append((val >> (16 * i)) & 0xFFFF)
                    if len(identify) >= 256:
                        identify_done, identify = identify[:256], None

    os.makedirs(args.out_dir, exist_ok=True)
    src = os.path.relpath(args.trace, ROOT).replace(os.sep, "/")
    with open(os.path.join(args.out_dir, "pci-config-reset.txt"), "w", newline="\n") as f:
        f.write(f"# PCI config reads before any write, from {src}\n")
        f.write("# Generated by tools/qemu-ref/fixtures.py; format: bdf reg size value\n")
        for (bdf, reg, size), val in sorted(pci_reads.items()):
            val &= (1 << 8 * size) - 1
            f.write(f"{bdf} {reg:#04x} {size} {val:#0{2 + 2 * size}x}\n")
    if len(edid) == 256:
        with open(os.path.join(args.out_dir, "edid-stdvga.txt"), "w", newline="\n") as f:
            f.write(f"# std VGA EDID (BAR 2 offset 0x000-0x0ff), from {src}\n")
            for row in range(16):
                f.write(" ".join(f"{edid[row * 16 + i]:02x}" for i in range(16)) + "\n")
    if identify_done:
        with open(os.path.join(args.out_dir, "atapi-identify.txt"), "w", newline="\n") as f:
            f.write(f"# IDENTIFY PACKET DEVICE words for the CD (ide1 master), from {src}\n")
            for row in range(32):
                f.write(" ".join(f"{w:04x}" for w in identify_done[row * 8:row * 8 + 8]) + "\n")
    print(f"pci reads: {len(pci_reads)}, edid bytes: {len(edid)}, "
          f"identify words: {len(identify_done or [])}")


if __name__ == "__main__":
    main()
