#!/usr/bin/env python3
"""Record the keyboard reference run for the input script machinery.

Boots an idle boot sector (sti; hlt loop) so SeaBIOS's IRQ1 handler reads
every byte the keyboard sends, then runs ref/input/keys.script: every
printable ASCII character typed, and every other key in the script key
table pressed and released on its own (lock keys excepted: SeaBIOS answers
them with LED commands whose ACKs would mix into the byte stream).

  ref/input/keys.script   the script
  ref/input/trace.log     the trace; its port 0x60 reads are the bytes

Then check that templeos.exe's script path sends exactly these bytes:

  cargo test -p devices --test replay_input -- --ignored
"""

import os
import string
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

SPECIAL = ["esc", "backspace", "tab", "ret", "ctrl", "shift", "shift_r", "alt", "spc",
           "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10", "f11", "f12",
           "kp_multiply", "kp_7", "kp_8", "kp_9", "kp_subtract", "kp_4", "kp_5", "kp_6",
           "kp_add", "kp_1", "kp_2", "kp_3", "kp_0", "kp_decimal", "less", "kp_enter",
           "ctrl_r", "kp_divide", "alt_r", "home", "up", "pgup", "left", "right", "end",
           "down", "pgdn", "insert", "delete", "meta_l", "meta_r", "compose", "print"]


def main():
    out = os.path.join(ROOT, "ref", "input")
    os.makedirs(out, exist_ok=True)
    disk = bytearray(1 << 20)
    disk[:4] = bytes([0xfb, 0xf4, 0xeb, 0xfd])  # sti; hlt; jmp hlt
    disk[510:512] = b"\x55\xaa"
    img = os.path.join(out, "idle.img")
    with open(img, "wb") as f:
        f.write(disk)

    printable = "".join(c for c in string.printable if c not in "\r\x0b\x0c")
    lines = ["# Generated by tools/qemu-ref/input_ref.py", "wait 3"]
    text = printable.replace("\\", "\\\\").replace("#", "\\#").replace("\n", "\\n").replace("\t", "\\t")
    lines.append("type " + text)
    lines += [f"key {k}" for k in SPECIAL]
    lines.append("wait 1")
    script = os.path.join(out, "keys.script")
    with open(script, "w") as f:
        f.write("\n".join(lines) + "\n")

    subprocess.run([sys.executable, os.path.join(HERE, "qemu_trace.py"), "--iso", "none",
                    "--hdd", img, "--script", script, "--out", out], check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
